apiVersion: v1
kind: Service
metadata:
  name: udagram-api-user-1
  labels:
    run: udagram-api-user-1
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    run: udagram-api-user-1