apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: abasiifrekeuwem/udagram-api-feed:v2
        ports:
        - containerPort: 8080
        env:
          - name: URL
            valueFrom:
              configMapKeyRef:
                name: udagram-env
                key: URL
          - name: AWS_BUCKET
            valueFrom:
              configMapKeyRef:
                name: udagram-env
                key: AWS_BUCKET
          - name: AWS_PROFILE
            valueFrom:
              configMapKeyRef:
                name: udagram-env
                key: AWS_PROFILE
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: udagram-env
                key: AWS_REGION
          - name: JWT_SECRET
            valueFrom:
              configMapKeyRef:
                name: udagram-env
                key: JWT_SECRET
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: udagram-env
                key: POSTGRES_DB
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: udagram-env
                key: POSTGRES_HOST
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: udagram-db-env
                key: POSTGRES_PASSWORD
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: udagram-db-env
                key: POSTGRES_USERNAME