apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy-1
  labels:
    app: reverseproxy-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reverseproxy-1
  template:
    metadata:
      labels:
        app: reverseproxy-1
    spec:
      containers:
      - name: reverseproxy-1
        image: abasiifrekeuwem/udagram-reverseproxy:v2
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      restartPolicy: Always